


































Timestep:  94%|██████████████████████████████████████████████████████████████████████████████████████▍     | 47/50 [00:32<00:02,  1.44it/s]

















Timestep:  94%|██████████████████████████████████████████████████████████████████████████████████████▍     | 47/50 [00:32<00:02,  1.43it/s]

















  File "/home/czr/anaconda3/envs/MM/lib/python3.8/site-packages/PIL/Image.py", line 3281, in open
    fp.seek(0)
AttributeError: 'Tensor' object has no attribute 'seek'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "experimental/ddpo_finetune.py", line 139, in <module>
    trainer.train()
  File "/home/czr/anaconda3/envs/MM/lib/python3.8/site-packages/trl/trainer/ddpo_trainer.py", line 604, in train
    global_step = self.step(epoch, global_step)
  File "/home/czr/anaconda3/envs/MM/lib/python3.8/site-packages/trl/trainer/ddpo_trainer.py", line 258, in step
    rewards, rewards_metadata = self.compute_rewards(
  File "/home/czr/anaconda3/envs/MM/lib/python3.8/site-packages/trl/trainer/ddpo_trainer.py", line 218, in compute_rewards
    reward, reward_metadata = self.reward_fn(images, prompts, prompt_metadata)
  File "experimental/ddpo_finetune.py", line 83, in wrapper_reward_fn
    score = reward_model.get_score([image], prompt)
  File "/home/czr/MM-Reward/./reward_models/score_reward_models.py", line 85, in get_clipscore
    images = [self.open_image(image) for image in images_path]
  File "/home/czr/MM-Reward/./reward_models/score_reward_models.py", line 85, in <listcomp>
    images = [self.open_image(image) for image in images_path]
  File "/home/czr/MM-Reward/./reward_models/score_reward_models.py", line 65, in open_image
    image = Image.open(image)
  File "/home/czr/anaconda3/envs/MM/lib/python3.8/site-packages/PIL/Image.py", line 3283, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'Tensor' object has no attribute 'read'